sudo: false

language: scala
scala:
  - 2.13.5
  - 2.12.13

dist: xenial
services:
  - xvfb

jdk:
  - openjdk11
  - openjdk15

install: true

script:
  - java -version
  - sbt test

# Disable testing broken branches
branches:
  except:
    - Scala3
