sudo: false

language: scala
scala:
  - 2.13.3
  - 2.12.12
  - 2.11.12

dist: xenial
services:
  - xvfb

jdk:
  - oraclejdk11
  - oraclejdk14
  - openjdk11
  - openjdk14

install: true

script:
  - java -version
  - sbt test

